meta_product_name: "Thanh Tran | Portfolio"
meta_title: "Thanh Tran - Freelance Web Developer"
meta_description: "RThanh Tran | Freelance Web Developer"
meta_image: "cover.png" # should exist in `app/assets/images/`
# twitter_account: "@product_twitter_account"   # required for Twitter Cards
